#load necessary packages (ggplot,rmarkdown,readxl)
library('rmarkdown');library('ggplot2');library('readxl');library(gridExtra)
pre.data<-read_excel("C:/Users/ncoker/Desktop/t-test sample files.xlsx",sheet="missing-dependent")
dependent<-as.data.frame(pre.data)
pre<-qplot(dependent$'max-pre',geom="histogram",binwidth=10)+xlab('1RM (kg)')+ylab('Frequency')+theme_classic()
post<-qplot(dependent$'max-post',geom="histogram",binwidth=10)+xlab('1RM (kg)')+ylab('Frequency')+theme_classic()
prepost<-grid.arrange(pre,post,nrow=1)